### PR TITLE
Competition api

### PR DESCRIPTION
**Pull request by tientruongisods**
# What does this PR solve and how
## What is this PR about?

- Develop api that can get all competition in mysql
- Create model Competition with attribute (Id, name, detail, data_path, created_user, created_date, start_at, end_at)
 path /api/competitions, get method
- Update and Delete competition from DB

## How to run it step by step
Step 1: in document app/ models.py

```
class Competition(models.Model):
    name = models.CharField(max_length=255)
    detail = models.TextField()
    data_path = models.CharField(max_length=255)
    created_user = models.CharField(max_length=255)
    created_date = models.DateTimeField(auto_now_add=True)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()

    def __str__(self):
        return self.name
```
Step 2: document/views.py

Get all competitions in DB
```
def get_all_competitions(request):
    competitions = list(Competition.objects.all().values())
    return JsonResponse(competitions, safe=False)
```
2. Update and Delete competition in DB
```

def update_competition(request, competition_id):
    try:
        competition = Competition.objects.get(id=competition_id)
    except Competition.DoesNotExist:
        return JsonResponse({'error': 'Competition does not exist.'}, status=404)

    if request.method == 'PUT':
        # update competition fields based on request data
        competition.name = request.POST.get('name', competition.name)
        competition.detail = request.POST.get('detail', competition.detail)
        competition.data_path = request.POST.get('data_path', competition.data_path)
        competition.start_at = request.POST.get('start_at', competition.start_at)
        competition.end_at = request.POST.get('end_at', competition.end_at)

        # save updated competition to database
        competition.save()

        return JsonResponse({'message': 'Competition updated successfully.'}, status=200)

    return JsonResponse({'error': 'Invalid request method.'}, status=400)
```
Step 3: Update urls.py in document

```
urlpatterns = [
    # Path to get all competitions
    path('competitions/', views.get_all_competitions, name='get_all_competitions'),

    # Path to update a competition by id
    path('competition/<int:id>/', views.update_competition, name='update_competition'),

    # Path to delete a competition by id
    path('competition/<int:id>/', views.delete_competition, name='delete_competition')
]

```
Step 4: Update admin.py in document

```
from .models import Competition

admin.site.register(Competition)
```
# Implementation 

# Testing
Run server http://127.0.0.1:8000/api/competitions/

# Risk
- 

# Dependencies
- 

# PR Checklist
- [ ] Documentation
- [ ] Unit testing passed
- [ ] Code review and discussion
- [ ] Approve
- [ ] Merge

### CODE REVIEW

**Comment by longnguyen-isods** [comment]
Hi Tien, can you merge this branch onto develop branch instead of master?  

Thank you!

**Comment by longnguyen-isods** [comment]
Hi Tien, 

I haven't checked your work, but your task is CRUD, which is Create, Read, Update, Delete. You have Read (all, we also need read a specific competition (id)); you have Update  with specific Id (which is great); you have Delete with specific Id (also great), but I wasn't able to test your API due to no Create API? I can manually create data in database, but it takes more time for me as well. Please implement Create API for Competition as well.

Also, include this on your model so when you make migrations, it is readable for your teammates.
```
class Meta: 
      db_table = 'Competition' 
```

Generally, nice work so far. Only needs to implement 1 more feature so I can test everything at once. 

Thank you

**Comment by tientruongisods** [comment]
> I haven't checked your work, but your task is CRUD, which is Create, Read, Update, Delete. You have Read (all, we also need read a specific competition (id)); you have Update with specific Id (which is great); you have Delete with specific Id (also great), but I wasn't able to test your API due to no Create API? I can manually create data in database, but it takes more time for me as well. Please implement Create API for Competition as well.

I will update it. Thanks Long!

**Review by longnguyen-isods — CHANGES_REQUESTED** [review]
Let me know when you've done it. 
Thanks

**Pull request closed without merging**
